version: '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles
    restart: always
    expose:
        - 7777
        - 27015
    volumes:
        - data:/conanexiles

volumes:
    data:
        driver: local
