version: '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles
    restart: always
    ports:
        - 7777:7777/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles

volumes:
    data:
        driver: local
